application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)
 )$


handlers:

- url: /resource
  static_dir: resource
  
- url: .*
  script: guestbook.app

libraries:
- name: webapp2
  version: "2.5.2"
